# THIS IS AN EXAMPLE SCHEMA THAT WAS IN USE IN A PRIOR VERSION OF THIS TOOL

# In the current version, this schema is to be pulled from the database

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

# schema that defines which fields should exist in a specified form version
# Also defines data validation conditions

SCHEMA = {
        "APGA-1.0": [
            {
                "wordFormColumn": "FY",
                "dataBaseColumnName": "FY",
                "dataBaseTableName": "Testing Table",
                "dataType": "integer",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Quarter",
                "dataBaseColumnName": "Q",
                "dataBaseTableName": "Testing Table",
                "dataType": "integer",
                "values": [1, 2, 3, 4],
                "required": True,
            },
            {
                "wordFormColumn": "Agency",
                "dataBaseColumnName": "Agency",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Goal",
                "dataBaseColumnName": "Goal",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Type",
                "dataBaseColumnName": "Type",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Ahead",
                "dataBaseColumnName": "Ahead",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": False,
            },
            {
                "wordFormColumn": "On Track",
                "dataBaseColumnName": "On_Track",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": False,
            },
            {
                "wordFormColumn": "Delayed",
                "dataBaseColumnName": "Delayed",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": False,
            },
            {
                "wordFormColumn": "Blocked",
                "dataBaseColumnName": "Blocked",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": False,
            },
            {
                "wordFormColumn": "Notes",
                "dataBaseColumnName": "Notes",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Quarterly Text",
                "dataBaseColumnName": "Quarterly_Text",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Key Result 1",
                "dataBaseColumnName": "KR1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Metric 1",
                "dataBaseColumnName": "M1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Start Value 1",
                "dataBaseColumnName": "SV1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Target Value 1",
                "dataBaseColumnName": "TV1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Current Value 1",
                "dataBaseColumnName": "CV1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Current As Of 1",
                "dataBaseColumnName": "CAO1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "No New Data 1",
                "dataBaseColumnName": "NND1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": False,
            },
            {
                "wordFormColumn": "Key Result 2",
                "dataBaseColumnName": "KR2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Metric 2",
                "dataBaseColumnName": "M2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Start Value 2",
                "dataBaseColumnName": "SV2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Target Value 2",
                "dataBaseColumnName": "TV2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Current Value 2",
                "dataBaseColumnName": "CV2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Current As Of 2",
                "dataBaseColumnName": "CAO2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "No New Data 2",
                "dataBaseColumnName": "NND2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Metric Type 1",
                "dataBaseColumnName": "MT1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Update Frequency 1",
                "dataBaseColumnName": "UF1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Footnote 1",
                "dataBaseColumnName": "F1",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Metric Type 2",
                "dataBaseColumnName": "MT2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Update Frequency 2",
                "dataBaseColumnName": "UF2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Footnote 2",
                "dataBaseColumnName": "F2",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
            {
                "wordFormColumn": "Version",
                "dataBaseColumnName": "Version",
                "dataBaseTableName": "Testing Table",
                "dataType": "string",
                "values": "any",
                "required": True,
            },
        ],
    }
